version: "3.8"

services:
  app:
    image: nullstone/rails:webapp-local
    volumes:
      - .:/app
      - gems:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "9000:9000"
    environment:
      - NULLSTONE_ENV=local
      - POSTGRES_URL=postgres://acme:acme@db:5432/acme
    depends_on:
      - db

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
      - POSTGRES_DB=acme

volumes:
  gems: {}
  node_modules: {}
