version: "3.8"

services:
  app:
    image: nullstone/rails:webapp
    entrypoint: /local.entrypoint.sh
    command: bundle exec rails server
    volumes:
      - .:/app
      - gem-cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - NULLSTONE_ENV=local
      - RAILS_ENV=development
      - POSTGRES_URL=postgres://acme:acme@db:5432/acme
    depends_on:
      - db

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
      - POSTGRES_DB=acme

volumes:
  gem-cache:
