version: "0.1"

subdomains:
  rails-webapp-subdomain:
    module: nullstone/aws-autogen-subdomain

apps:
  rails-webapp-quickstart:
    module: nullstone/aws-fargate-service
    vars:
      cpu: 256
      memory: 512
      port: 80
    capabilities:
      - module: nullstone/rails-cookies
      - module: nullstone/aws-fargate-nginx-sidecar
        vars:
          webapp_addr: "localhost:9000"
      - module: nullstone/aws-load-balancer
        connections:
          subdomain: rails-webapp-subdomain
      - module: aws-postgres-access
        connections:
          postgres: postgres
